# IDA: Assignment 2

### Deadline: October 3 (until 23:59)


**Instructions:** All answers should be provided in the notebook and then submitted to Moodle. Name of notebook should be in following format:
 - Name_group_Assignment2.ipynb (ex. Tony_Stark_2009_Assignment1.ipynb). PLEASE, use exactly the **same format.**
 - Try to use fewer cells for compilation (for example, you can use print for several answers, instead of printing each answer on a separate cell)
 - **PLEASE:** submit only one jupyter notebook (no zip or csv files) and with your names as in the instruction. Ohterwise, there will be punishment of 30% from your assignment mark.
 - **IMPORTANT NOTE:** you will get points only for correct answers, not for trials or wrong answers. Your notebook should run when we press **"Restart Kernel"** and then press **"Run All"**. We are going to check answers only after doing that. If your code do not compile and stops at any question, you will get zero for that question.

## Q1 (10%)
Using **list comprehension** create a new list from `list_q1_1` and `list_q1_2`. For the values at the same position (index), you should have sum of elements if element of `list_q1_1` is smaller (strictly) than the element of `list_q1_2`. Otherwise, you should take their difference. 

***Note:*** *in the obtained list all values should be positive.*

In [1]:
list_q1_1 = [41, 21, 96, 34, 65, 46, 79, 73, 49, 85, 63, 51, 93, 84, 29, 62, 95, 39, 72, 66]
print(list_q1_1)

[41, 21, 96, 34, 65, 46, 79, 73, 49, 85, 63, 51, 93, 84, 29, 62, 95, 39, 72, 66]


In [2]:
list_q1_2 = [95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]
print(list_q1_2)

[95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]


In [3]:
print([abs(i + j) if i < j else abs(i - j) for i, j in zip(list_q1_1, list_q1_2)])

[136, 97, 4, 125, 16, 107, 11, 41, 99, 56, 15, 133, 60, 3, 68, 131, 11, 113, 161, 51]


## Q2 (10%)
Using **list comprehension** on `list_q2_1` and `list_q2_2` create a new list containing value pairs, where one of them is divisible by another, but do not include two equal elements. For example, (13, 91) should be included, but (91,91) should not).

In [4]:
list_q2_1 = [97, 29, 43, 96, 91, 22, 51, 83, 31, 13,
             62, 19, 23, 26, 50, 70, 84, 67, 36, 35]
print(list_q2_1)

[97, 29, 43, 96, 91, 22, 51, 83, 31, 13, 62, 19, 23, 26, 50, 70, 84, 67, 36, 35]


In [5]:
list_q2_2 = [31, 63, 98, 91, 46, 71, 37, 70, 75, 33,
             74, 77, 40, 10, 11, 57, 84, 64, 18, 28]
print(list_q2_2)

[31, 63, 98, 91, 46, 71, 37, 70, 75, 33, 74, 77, 40, 10, 11, 57, 84, 64, 18, 28]


In [6]:
print([(i, j) for i in list_q2_1 for j in list_q2_2 if ((i % j == 0 or j % i == 0) and i != j)])

[(22, 11), (13, 91), (62, 31), (19, 57), (23, 46), (50, 10), (70, 10), (84, 28), (36, 18), (35, 70)]


## Q3 (10%)
Using **list comprehension** obtain a list of all 2-digits prime numbers (for example, 13, 17, 19...).

***Note:*** *it can be done with one line of code.*

In [7]:
print([n for n in range(11, 100, 2) if all(n % i != 0 for i in range(2, n))])

[11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## Q4 (10%)


Using **list comprehension** create a windowing lists of 3 elements at a time with step 1 for `list_q4`. 

Your result should look as following: [[48, 95, 11], [95, 11, 46], [11, 46, 76],..]

***Note:*** *it can be done with one line of code.*

In [8]:
list_q4 = [48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 
           17, 26, 97, 63, 93, 57, 28, 85, 54, 62]
print(list_q4)

[48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 17, 26, 97, 63, 93, 57, 28, 85, 54, 62]


In [9]:
print([[list_q4[j] for j in range(i, i + 3) if i + 3 <= len(list_q4)] for i in range(len(list_q4))][:-2])

[[48, 95, 11], [95, 11, 46], [11, 46, 76], [46, 76, 75], [76, 75, 35], [75, 35, 78], [35, 78, 81], [78, 81, 58], [81, 58, 17], [58, 17, 26], [17, 26, 97], [26, 97, 63], [97, 63, 93], [63, 93, 57], [93, 57, 28], [57, 28, 85], [28, 85, 54], [85, 54, 62]]


## Q5 (10%)
For the string below using **dictionary comprihension** create a dictionary, where key - possible word length, and value - number of words of this length. 

***Note:*** *you should not consider keys which are not appearing in the text.*

In [10]:
string_q5 = "From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but."
print(string_q5)

From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but.


In [11]:
print({i : [len(i) for i in string_q5.replace('.', ' ').split()].count(i) for i in [len(j) for j in string_q5.replace('.', ' ').split()]})

{4: 13, 2: 22, 3: 26, 9: 15, 10: 15, 6: 9, 8: 10, 5: 10, 7: 4}


## Q6 (10%)
Using numpy create two arbitrary matrices A and B of size 3x3 with only 2-digit numbers. And then apply different matrix operations:
1. addition
2. subtraction
3. pointwise multiplication
4. pointwise division
5. matrix dot product
6. transpose
7. determinant
8. rank
9. inverse

In [12]:
import numpy as np

In [13]:
import random

def Addition(A, B):
    res = np.add(A, B)
    print('\nAddition:\n', res)

def Substraction(A, B):
    res = np.subtract(A, B)
    print('\nSubstraction:\n' , res)

def Pointw_Mult(A, B):
    res = np.multiply(A, B)
    print('\nPointwise multuplication:\n', res)

def Pointw_Div(A, B):
    res = np.divide(A, B)
    print('\nPointwise division:\n', res)

def Dot_Prod(A, B):
    res = np.dot(A, B)
    print('\nMatrix dot product:\n', res)

def Transpose(matr1, matr2):
    res1 = np.transpose(matr1)
    res2 = np.transpose(matr2)
    print('\nTranspose of the matrix A:\n', res1)
    print('\nTranspose of the matrix B:\n', res2)

def Determinant(matr1, matr2):
    res1 = np.linalg.det(matr1)
    res2 = np.linalg.det(matr2)
    print('\nDeterminant of the matrix A:\n', res1)
    print('\nDeterminant of the matrix B:\n', res2)

def Rank(matr1, matr2):
    res1 = np.linalg.matrix_rank(matr1)
    res2 = np.linalg.matrix_rank(matr2)
    print('\nRank of the matrix A:\n', res1)
    print('\nRank of the matrix B:\n', res2)

def Inverse(matr1, matr2):
    res1 = np.linalg.inv(matr1)
    res2 = np.linalg.inv(matr2)
    print('\nInverse of the matrix A:\n', res1)
    print('\nInverse of the matrix B:\n', res2)

A = np.matrix([random.randint(10, 99) for i in range(9)]).reshape(3, 3)
B = np.matrix([random.randint(10, 99) for i in range(9)]).reshape(3, 3)
print('The matrix A:\n', A, '\n')
print('The matrix B:\n', B)

Addition(A, B)
Substraction(A, B)
Pointw_Mult(A, B)
Pointw_Div(A, B)
Dot_Prod(A, B)
Transpose(A, B)
Determinant(A, B)
Rank(A, B)
Inverse(A, B)

The matrix A:
 [[62 76 30]
 [18 96 75]
 [52 73 70]] 

The matrix B:
 [[53 39 50]
 [64 23 42]
 [44 90 65]]

Addition:
 [[115 115  80]
 [ 82 119 117]
 [ 96 163 135]]

Substraction:
 [[  9  37 -20]
 [-46  73  33]
 [  8 -17   5]]

Pointwise multuplication:
 [[3286 2964 1500]
 [1152 2208 3150]
 [2288 6570 4550]]

Pointwise division:
 [[1.16981132 1.94871795 0.6       ]
 [0.28125    4.17391304 1.78571429]
 [1.18181818 0.81111111 1.07692308]]

Matrix dot product:
 [[ 9470  6866  8242]
 [10398  9660  9807]
 [10508 10007 10216]]

Transpose of the matrix A:
 [[62 18 52]
 [76 96 73]
 [30 75 70]]

Transpose of the matrix B:
 [[53 64 44]
 [39 23 90]
 [50 42 65]]

Determinant of the matrix A:
 167490.0

Determinant of the matrix B:
 26127.000000000004

Rank of the matrix A:
 3

Rank of the matrix B:
 3

Inverse of the matrix A:
 [[ 0.00743328 -0.01868768  0.01683683]
 [ 0.01576214  0.01659801 -0.02453878]
 [-0.02195952 -0.00342707  0.0273688 ]]

Inverse of the matrix B:
 [[-0.08745742  0.07520955  0

## Q7 (10%)
For the list below obtain numpy array and then do the following steps:
1. Find all indexes for values between 40 and 60 (both included).
2. Find all values between 40 and 60 (both included).
3. Find all numbers divisible by 3 or 5 or 7.
4. Find all prime numbers in this array (you may use list obtained in Q3).

In [14]:
list_q7 = [53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 
           15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 
           90, 13, 23, 54, 80, 83, 98, 14, 70, 30]
print(list_q7)

[53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 90, 13, 23, 54, 80, 83, 98, 14, 70, 30]


In [15]:
import numpy as np

arr = np.array(list_q7)
print('Array:', arr)
print('1)', *[i for i in range(len(arr)) if 40 <= arr[i] <= 60])
print('2)', *[arr[i] for i in range(len(arr)) if 40 <= arr[i] <= 60])
print('3)', *[arr[i] for i in range(len(arr)) if arr[i] % 3 == 0 or arr[i] % 5 == 0 or arr[i] % 7 == 0])
print('4)', *[arr[i] for i in range(len(arr)) if arr[i] in [n for n in range(11, 100, 2) if all(n % i != 0 for i in range(2, n))]])

Array: [53 58 93 96 40 97 95 24 27 61 15 25 47 22 45 50 99 37 13 17 90 13 23 54
 80 83 98 14 70 30]
1) 0 1 4 12 14 15 23
2) 53 58 40 47 45 50 54
3) 93 96 40 95 24 27 15 25 45 50 99 90 54 80 98 14 70 30
4) 53 97 61 47 37 13 17 13 23 83


## Q8 (10%)
Do the following tasks:
1. Create an array of all 3-digit numbers divisible by 33. 
2. Create an array of 19 elements betweem 10 and 100.
3. Create an array of size 20 with random 2-digit values. Replace all numbers divisible by 3 to 'abc'.
4. Create an array of size 20 with random 2-digit values. Find 3 smallest and 3 largest elements. 

In [16]:
import numpy as np, random

arr1 = np.array([i for i in range(100, 1000) if i % 33 == 0])
arr2 = np.array([random.randint(10, 100) for i in range(19)])
arr3 = np.array([i if i % 3 != 0 else 'abc' for i in [random.randint(10, 99) for j in range(20)]])
arr4 = np.array([random.randint(10, 99) for j in range(20)])
print('1)', arr1, '\n')
print('2)', arr2, '\n')
print('3)', arr3, '\n')
print('4)', arr4, '\nSmallest 3:', np.sort(arr4)[:3], 'Largest 3:', np.sort(arr4)[len(arr4) - 3:])

1) [132 165 198 231 264 297 330 363 396 429 462 495 528 561 594 627 660 693
 726 759 792 825 858 891 924 957 990] 

2) [ 81  49  10  91  23  87  47  23  36  26  83  62  53 100  71  66  24  71
  67] 

3) ['35' '68' '77' '91' 'abc' '62' '49' '50' '88' '83' 'abc' '85' 'abc' '19'
 '68' '20' 'abc' '22' '77' 'abc'] 

4) [15 51 19 20 54 63 78 30 59 24 99 19 18 69 89 44 89 43 95 65] 
Smallest 3: [15 18 19] Largest 3: [89 95 99]


## Q9 (10%)
Create a matrix of size 4x4 with random 2-digit numbers. Do the following tasks:
1. Find mean along rows and mean along columns.
2. Find max along rows and max along columns.
3. Find indexes of min and max values.
4. Iteratre over matrix, and print its index as (i,j) and corresponding value. For example, Index: (1,1), Value: 50.

In [17]:
import numpy as np, random

def Matr_Means(mt):
    print('\nColumn means:\n', mt.mean(axis=0))
    print('\nRow means:\n', mt.mean(axis=1))

def Matr_Max(mt):
    print('\nMaximums along columns:\n', mt.max(axis=0))
    print('\nMaximums along rows:\n', mt.max(axis=1))

def Ind_of_MaxMin(mt):
    ind_max = np.argmax(mt)
    ind_min = np.argmin(mt)
    print('\nIndex of maximum in the entire matrix:', np.unravel_index(ind_max, mt.shape))
    print('The maximum in the entire matrix:', mt[np.unravel_index(ind_max, mt.shape)])
    print('\nIndex of minimum in the entire matrix:', np.unravel_index(ind_min, mt.shape))
    print('The minimum in the entire matrix:', mt[np.unravel_index(ind_min, mt.shape)])

def Iterate(mt):
    print()
    for index, values in np.ndenumerate(mt):
        print('Index: {}, Value: {}'.format(index, values)) 

matr = np.matrix([random.randint(10, 99) for i in range(16)]).reshape(4, 4)
print('Matrix:\n', matr)

Matr_Means(matr)
Matr_Max(matr)
Ind_of_MaxMin(matr)
Iterate(matr)

Matrix:
 [[85 28 68 29]
 [54 13 95 67]
 [48 36 99 56]
 [78 91 64 33]]

Column means:
 [[66.25 42.   81.5  46.25]]

Row means:
 [[52.5 ]
 [57.25]
 [59.75]
 [66.5 ]]

Maximums along columns:
 [[85 91 99 67]]

Maximums along rows:
 [[85]
 [95]
 [99]
 [91]]

Index of maximum in the entire matrix: (2, 2)
The maximum in the entire matrix: 99

Index of minimum in the entire matrix: (1, 1)
The minimum in the entire matrix: 13

Index: (0, 0), Value: 85
Index: (0, 1), Value: 28
Index: (0, 2), Value: 68
Index: (0, 3), Value: 29
Index: (1, 0), Value: 54
Index: (1, 1), Value: 13
Index: (1, 2), Value: 95
Index: (1, 3), Value: 67
Index: (2, 0), Value: 48
Index: (2, 1), Value: 36
Index: (2, 2), Value: 99
Index: (2, 3), Value: 56
Index: (3, 0), Value: 78
Index: (3, 1), Value: 91
Index: (3, 2), Value: 64
Index: (3, 3), Value: 33


## Q10 (10%)
Create a matrix of size 5x5 with random 2-digit numbers. Do the following tasks:
1. Reverse both along rows and columns.
2. Sort along rows in descending order.
3. Sort along columns in descending order.
4. Sort all 25 elements in descending order, i.e. at index (1,1) you should have the largest element, and at index (5,5) the smallest element. 

In [18]:
import numpy as np, random

def Matr_Reverse(mt):
    print('\nReversed matrix:\n', np.flip(mt))

def Matr_SortByRows(mt):
    v = mt.tolist()
    d = {}
    for i in v:
        if sum(i) not in d.keys():
            d[sum(i)] = [i]
        else:
            d[sum(i)].append(i)
    res = []
    for key in sorted(d.keys(), key=int, reverse=True):
        for value in d[key]:
            res.append(value)
    mt = np.matrix(res)
    print('\nSorted rows of matrix in descending order:\n', mt)

def Matr_SortByColumns(mt):
    v = list(zip(*np.asarray(mt)))
    res1 = [list(i) for i in v]
    d = {}
    for i in res1:
        if sum(i) not in d.keys():
            d[sum(i)] = [i]
        else:
            d[sum(i)].append(i)
    res2 = []
    for key in sorted(d.keys(), key=int, reverse=True):
        for value in d[key]:
            res2.append(value)
    mt = np.matrix(res2)
    mt = mt.transpose()
    print('\nSorted columns of matrix in descending order:\n', mt)

def All_Sort(mt):
    v = mt.tolist()
    res = []
    for i in v:
        for j in i:
            res.append(j)
    mt = np.matrix(sorted(res, key=int, reverse=True)).reshape(5, 5)
    print('\nFull sorted matrix by descending order:\n', mt)

matr = np.matrix([random.randint(10, 99) for i in range(25)]).reshape(5, 5)
print('Matrix:\n', matr)

Matr_Reverse(matr)
Matr_SortByRows(matr)
Matr_SortByColumns(matr)
All_Sort(matr)

Matrix:
 [[91 49 71 35 90]
 [79 81 43 43 58]
 [34 66 78 43 96]
 [25 67 68 37 90]
 [81 15 13 31 87]]

Reversed matrix:
 [[87 31 13 15 81]
 [90 37 68 67 25]
 [96 43 78 66 34]
 [58 43 43 81 79]
 [90 35 71 49 91]]

Sorted rows of matrix in descending order:
 [[91 49 71 35 90]
 [34 66 78 43 96]
 [79 81 43 43 58]
 [25 67 68 37 90]
 [81 15 13 31 87]]

Sorted columns of matrix in descending order:
 [[90 91 49 71 35]
 [58 79 81 43 43]
 [96 34 66 78 43]
 [90 25 67 68 37]
 [87 81 15 13 31]]

Full sorted matrix by descending order:
 [[96 91 90 90 87]
 [81 81 79 78 71]
 [68 67 66 58 49]
 [43 43 43 37 35]
 [34 31 25 15 13]]


---

### Evaluation (Keep it!)

| Question | Mark     | Comment   
|:-------:|:--------:|:----------------------
| 1       |   10/10    |     
| 2       |   10/10     | 
| 3       |   10/10     | 
| 4       |   10/10     | 
| 5       |   10/10    |     
| 6       |   10/10     | 
| 7       |   10/10     | 
| 8       |   10/10     | 
| 9       |   10/10     | 
| 10       |   10/10     | 
|**Total**|**100/100**  | 
